{% set name = "autograd-gamma" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2cb570cbb8da61ede937ccc004d87d3924108f754b351a86cdd2ad31ace6cdf6

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
  run:
    - python
    - autograd >=1.2.0
    - scipy >=1.2.0

test:
  imports:
    - autograd_gamma

about:
  home: https://github.com/CamDavidsonPilon/autograd-gamma
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Autograd compatible approximations to the gamma family of functions
  dev_url: https://github.com/CamDavidsonPilon/autograd-gamma

extra:
  recipe-maintainers:
    - mariusvniekerk
    - CamDavidsonPilon
